import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../analytics/scan_analytics.dart';
import '../core/theme/app_theme.dart';
import '../utils/download_helper.dart';

/// Builds and saves a printable PDF report of the Admin analytics that are
/// currently displayed on screen (period + farm scope).
class AnalyticsPdfService {
  /// Renders the analytics snapshot as a PDF document (pure Dart, web-safe).
  static Future<Uint8List> buildAnalyticsPdf({
    required ScanAnalytics analytics,
    required AnalyticsPeriod period,
    required String scopeLabel,
    required DateTime generatedAt,
    required int totalUsers,
    required int activeFarmers,
    required int pendingSchedules,
    required int completedSchedules,
    required int archivedRecords,
  }) async {
    final doc = pw.Document(
      title: 'SFARMING Scan Analytics Report',
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
      ),
    );

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by SFARMING',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
            ),
          ],
        ),
        build: (context) => _buildSections(
          analytics,
          period,
          scopeLabel,
          generatedAt,
          totalUsers,
          activeFarmers,
          pendingSchedules,
          completedSchedules,
          archivedRecords,
        ),
      ),
    );

    return doc.save();
  }

  /// Saves [bytes] to disk on mobile/desktop or via browser blob on web.
  static Future<bool> downloadAnalyticsPdf({
    required BuildContext context,
    required Uint8List bytes,
    required String fileName,
  }) async {
    try {
      if (kIsWeb) {
        saveFileWeb(bytes, fileName);
        if (context.mounted) {
          _showSnackBar(context, 'Analytics report downloaded: $fileName');
        }
        return true;
      }

      Directory? dir;
      if (Platform.isAndroid) {
        dir = Directory('/storage/emulated/0/Download');
        if (!await dir.exists()) {
          dir = await getExternalStorageDirectory();
        }
      } else {
        dir = await getApplicationDocumentsDirectory();
      }
      dir ??= await getTemporaryDirectory();

      final file = File('${dir.path}/$fileName');
      await file.writeAsBytes(bytes);

      if (context.mounted) {
        _showSnackBar(context, 'Analytics report saved: $fileName');
      }
      return true;
    } catch (e) {
      if (context.mounted) {
        _showSnackBar(
          context,
          'Failed to download analytics report: $e',
          isError: true,
        );
      }
      return false;
    }
  }

  static List<pw.Widget> _buildSections(
    ScanAnalytics analytics,
    AnalyticsPeriod period,
    String scopeLabel,
    DateTime generatedAt,
    int totalUsers,
    int activeFarmers,
    int pendingSchedules,
    int completedSchedules,
    int archivedRecords,
  ) {
    final (rangeStart, rangeEnd) = analyticsPeriodRange(period, generatedAt);
    final rangeEndLabel = rangeEnd.subtract(const Duration(days: 1));
    final rangeLabel = period == AnalyticsPeriod.today
        ? DateFormat('MMM d, yyyy').format(rangeStart)
        : '${DateFormat('MMM d, yyyy').format(rangeStart)} – '
            '${DateFormat('MMM d, yyyy').format(rangeEndLabel)}';

    return [
      // ── Header banner ──────────────────────────────────────────────────
      pw.Container(
        padding: const pw.EdgeInsets.all(16),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromInt(AppTheme.brandPrimary.toARGB32()),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'SFARMING',
              style: pw.TextStyle(
                color: PdfColors.white,
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Scan Analytics Report',
              style: const pw.TextStyle(color: PdfColors.white, fontSize: 15),
            ),
          ],
        ),
      ),
      pw.SizedBox(height: 16),

      // ── Scope & metadata ───────────────────────────────────────────────
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Scope: $scopeLabel',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
          ),
          pw.Text(
            'Generated: ${DateFormat('MMM d, yyyy · h:mm a').format(generatedAt)}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
          ),
        ],
      ),
      pw.SizedBox(height: 2),
      pw.Text(
        'Period: ${analyticsPeriodLabel(period, generatedAt)} · $rangeLabel',
        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
      ),
      pw.SizedBox(height: 20),

      // ── System overview ────────────────────────────────────────────────
      _sectionTitle('1. System Overview'),
      pw.SizedBox(height: 8),
      pw.TableHelper.fromTextArray(
        headers: ['Metric', 'Value'],
        data: [
          ['Total users', '$totalUsers'],
          ['Active farmers', '$activeFarmers'],
          ['Pending schedules', '$pendingSchedules'],
          ['Completed schedules', '$completedSchedules'],
          ['Archived records', '$archivedRecords'],
        ],
        headerDecoration: _headerDecoration(),
        headerStyle: _headerTextStyle(),
        cellStyle: _cellTextStyle(),
        columnWidths: const {0: pw.FlexColumnWidth(2), 1: pw.FlexColumnWidth(1)},
        border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.6),
      ),
      pw.SizedBox(height: 20),

      // ── Scan summary ───────────────────────────────────────────────────
      _sectionTitle('2. Scan Summary'),
      pw.SizedBox(height: 8),
      pw.TableHelper.fromTextArray(
        headers: ['Disease / Result', 'Count', 'Share of valid scans'],
        data: [
          ['Total Valid Scans', '${analytics.totalValidScans}', '100%'],
          for (final c in kAnalyticsCategories)
            [
              c,
              '${analytics.counts[c] ?? 0}',
              analytics.totalValidScans == 0
                  ? '0%'
                  : '${analytics.percentageOf(c).toStringAsFixed(0)}%',
            ],
        ],
        headerDecoration: _headerDecoration(),
        headerStyle: _headerTextStyle(),
        cellStyle: _cellTextStyle(),
        border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.6),
      ),
      pw.SizedBox(height: 20),

      // ── Disease distribution ───────────────────────────────────────────
      _sectionTitle('3. Disease Distribution'),
      pw.SizedBox(height: 8),
      _distributionTable(analytics),
      pw.SizedBox(height: 20),

      // ── Disease trend ──────────────────────────────────────────────────
      _sectionTitle('4. Disease Trend'),
      pw.SizedBox(height: 8),
      pw.SizedBox(height: 180, child: _trendChart(analytics)),
      pw.SizedBox(height: 16),

      // ── Key insights ───────────────────────────────────────────────────
      _sectionTitle('5. Key Insights'),
      pw.SizedBox(height: 8),
      for (final insight in generateScanInsights(analytics))
        pw.Bullet(text: insight, style: _cellTextStyle()),
      pw.SizedBox(height: 20),

      // ── Footnote ───────────────────────────────────────────────────────
      pw.Text(
        'Percentages are based on valid scans only. Invalid scans are excluded from all statistics.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
      ),
    ];
  }

  static pw.Widget _distributionTable(ScanAnalytics analytics) {
    final rows = <pw.TableRow>[
      _tableRowHeader('Disease', 'Count', 'Share of valid scans'),
      for (final c in kAnalyticsCategories)
        _tableRow(
          c,
          '${analytics.counts[c] ?? 0}',
          analytics.totalValidScans == 0
              ? '0%'
              : '${analytics.percentageOf(c).toStringAsFixed(0)}%',
          PdfColor.fromInt(
            analyticsColorFor(c, kAnalyticsCategories.indexOf(c)).toARGB32(),
          ),
        ),
    ];
    return pw.Table(
      columnWidths: const {0: pw.FlexColumnWidth(3), 1: pw.FlexColumnWidth(1), 2: pw.FlexColumnWidth(2)},
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.6),
      children: rows,
    );
  }

  static pw.Widget _trendChart(ScanAnalytics analytics) {
    final labels = analytics.trendLabels;
    final yMax = analytics.maxTrendValue < 1 ? 1 : analytics.maxTrendValue;
    const axisStyle = pw.TextStyle(fontSize: 8, color: PdfColors.grey700);

    return pw.Chart(
      grid: pw.CartesianGrid(
        xAxis: pw.FixedAxis.fromStrings(
          labels,
          textStyle: axisStyle,
          margin: 6,
          divisions: true,
          divisionsColor: PdfColors.grey300,
          divisionsWidth: 0.5,
        ),
        yAxis: pw.FixedAxis<int>(
          _niceTicks(yMax),
          textStyle: axisStyle,
          margin: 8,
          divisions: true,
          divisionsColor: PdfColors.grey300,
          divisionsWidth: 0.5,
        ),
      ),
      datasets: [
        pw.BarDataSet(
          data: [
            for (var i = 0; i < labels.length; i++)
              pw.PointChartValue(
                i.toDouble(),
                (analytics.trendCounts[labels[i]] ?? 0).toDouble(),
              ),
          ],
          color: PdfColor.fromInt(AppTheme.brandPrimary.toARGB32()),
          width: labels.length > 8 ? 7 : 14,
          valuePosition: pw.ValuePosition.top,
          buildValue: (context, value) => pw.Text(
            value.y.toInt().toString(),
            style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey800),
          ),
        ),
      ],
    );
  }

  static List<int> _niceTicks(int maxValue) {
    final step = ((maxValue / 5).ceil()).clamp(1, maxValue);
    final ticks = <int>[];
    for (var v = 0; v < maxValue; v += step) {
      ticks.add(v);
    }
    if (ticks.isEmpty || ticks.last != maxValue) {
      ticks.add(maxValue);
    }
    return ticks;
  }

  static pw.Widget _sectionTitle(String text) {
    return pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: 13,
        fontWeight: pw.FontWeight.bold,
        color: PdfColor.fromInt(AppTheme.brandPrimary.toARGB32()),
      ),
    );
  }

  static pw.TableRow _tableRowHeader(String a, String b, String c) {
    return pw.TableRow(
      decoration: _headerDecoration(),
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(a, style: _headerTextStyle()),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(b, style: _headerTextStyle()),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(c, style: _headerTextStyle()),
        ),
      ],
    );
  }

  static pw.TableRow _tableRow(String name, String count, String share, PdfColor color) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Row(
            children: [
              pw.Container(
                width: 10,
                height: 10,
                decoration: pw.BoxDecoration(color: color),
              ),
              pw.SizedBox(width: 6),
              pw.Text(name, style: _cellTextStyle()),
            ],
          ),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(count, style: _cellTextStyle()),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(share, style: _cellTextStyle()),
        ),
      ],
    );
  }

  static pw.BoxDecoration _headerDecoration() {
    return pw.BoxDecoration(color: PdfColor.fromInt(AppTheme.brandPrimary.toARGB32()));
  }

  static pw.TextStyle _headerTextStyle() {
    return pw.TextStyle(
      color: PdfColors.white,
      fontSize: 9,
      fontWeight: pw.FontWeight.bold,
    );
  }

  static pw.TextStyle _cellTextStyle() {
    return const pw.TextStyle(fontSize: 9, color: PdfColors.grey900);
  }

  static void _showSnackBar(BuildContext context, String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red.shade700 : Colors.green.shade700,
        duration: const Duration(seconds: 3),
      ),
    );
  }
}
